### ISSUE TITLE
Build in Ubuntu Focal Fossa needs more dependencies than the build docs list

### ISSUE THREAD

**Issue by josephbburg** [sfztools/sfztools.github.io#8]
In order to successfully configure the cmake files for sfizz, I had to install more dependencies than https://sfz.tools/sfizz/development/build/linux lists. 
In all, I needed `libxcb-utils-dev` `libxcb-cursor-dev` `libxcb-keysyms1-dev` `lib-xkb-dev` `libxkbcommon-x11-dev` to succesfully configure the Cmake file (step 4, `cmake ..`).
After that, it succesfully built with `make` and `sudo make install`. Can't wait to try it out!

**Comment by josephbburg** [comment]
Somehow I put this issue in the wrong Git page, Sorry for the noise, will move this to the correct repo.

**Comment by redtide** [comment]
Hello! I think the issue was in the right place, this is the documentation website project and the issue is about the documentation. No noise at all and thank you for reporting this!
